<optgroup label="🏠 Interior - Principiantes (Casi inmortales)">
    <option value="sansevieria">Lengua de Suegra (Sansevieria)</option>
    <option value="zamioculcas">Planta ZZ (Zamioculcas)</option>
    <option value="potos">Potos (Teléfono)</option>
    <option value="cinta">Cinta (Malamadre/Lazo de amor)</option>
    <option value="arbol_jade">Árbol de Jade (Crassula ovata)</option>
    <option value="aloe_vera">Aloe Vera (Sábila)</option>
    <option value="cactus_navidad">Cactus de Navidad (Schlumbergera)</option>
    <option value="aspidistra">Aspidistra (Pilistra)</option>
</optgroup>
<optgroup label="🌿 Interior - Tropicales (Requieren mimo)">
    <option value="monstera">Costilla de Adán (Monstera deliciosa)</option>
    <option value="spathi">Lirio de la Paz (Cuna de Moisés)</option>
    <option value="ficus_lyrata">Ficus Lira (Higuera hoja de violín)</option>
    <option value="ficus_elastica">Ficus Elástica (Árbol de caucho)</option>
    <option value="calathea">Calathea (Planta Oración)</option>
    <option value="maranta">Maranta (Prima de la Calathea)</option>
    <option value="helecho_boston">Helecho de Boston</option>
    <option value="anturio">Anturio (Flor roja)</option>
    <option value="dieffenbachia">Diefembaquia (Lotería)</option>
    <option value="aglaonema">Aglaonema</option>
    <option value="croton">Crotón (Hojas de colores)</option>
    <option value="palma_areca">Palma Areca</option>
    <option value="peperomia">Peperomia (Cucharita)</option>
    <option value="begonia_maculata">Begonia Maculata (Alas de ángel)</option>
    <option value="alocasia">Alocasia (Oreja de Elefante)</option>
    <option value="orquidea">Orquídea Phalaenopsis</option>
</optgroup>
<optgroup label="🌵 Cactus y Suculentas (Amantes del sol)">
    <option value="echeveria">Echeveria (Rosa de alabastro)</option>
    <option value="haworthia">Haworthia (Planta cebra)</option>
    <option value="sedum">Sedum (Cola de burro)</option>
    <option value="nopal">Nopal (Opuntia)</option>
    <option value="cactus_barril">Cactus Barril (Echinocactus)</option>
    <option value="kalanchoe">Kalanchoe</option>
</optgroup>
<optgroup label="🌸 Exterior - Flores y Ornamentales">
    <option value="geranio">Geranio</option>
    <option value="rosal">Rosal</option>
    <option value="buganvilla">Buganvilla (Santa Rita/Veranera)</option>
    <option value="hortensia">Hortensia</option>
    <option value="lavanda">Lavanda</option>
    <option value="petunia">Petunia</option>
    <option value="tagete">Cempasúchil (Tagete/Clavel moro)</option>
    <option value="hibisco">Hibisco (Rosa de China)</option>
    <option value="jazmin">Jazmín</option>
    <option value="gardenia">Gardenia</option>
    <option value="azalea">Azalea</option>
    <option value="crisantemo">Crisantemo</option>
    <option value="girasol">Girasol</option>
    <option value="tulipan">Tulipán</option>
</optgroup>
<optgroup label="🍅 Huerto - Hortalizas">
    <option value="tomate">Tomatera</option>
    <option value="lechuga">Lechuga</option>
    <option value="zanahoria">Zanahoria</option>
    <option value="pimiento">Pimiento / Chile</option>
    <option value="pepino">Pepino</option>
    <option value="calabacin">Calabacín (Zucchini)</option>
    <option value="espinaca">Espinaca</option>
    <option value="cebolla">Cebolla</option>
    <option value="ajo">Ajo</option>
    <option value="patata">Patata / Papa</option>
    <option value="rabano">Rábano</option>
    <option value="berenjena">Berenjena</option>
    <option value="calabaza">Calabaza</option>
    <option value="judia">Judía Verde / Ejote</option>
    <option value="guisante">Guisante / Chícharo</option>
    <option value="fresa">Fresas</option>
</optgroup>
<optgroup label="🌿 Huerto - Aromáticas">
    <option value="albahaca">Albahaca</option>
    <option value="menta">Menta / Hierbabuena</option>
    <option value="romero">Romero</option>
    <option value="tomillo">Tomillo</option>
    <option value="oregano">Orégano</option>
    <option value="perejil">Perejil</option>
    <option value="cilantro">Cilantro</option>
    <option value="salvia">Salvia</option>
    <option value="eneldo">Eneldo</option>
    <option value="cebollino">Cebollino (Ciboulette)</option>
    <option value="laurel">Laurel</option>
</optgroup>
<optgroup label="🌳 Árboles Frutales y Decorativos">
    <option value="limonero">Limonero</option>
    <option value="naranjo">Naranjo</option>
    <option value="olivo">Olivo</option>
    <option value="manzano">Manzano</option>
    <option value="peral">Peral</option>
    <option value="higuera">Higuera</option>
    <option value="papaya">Papaya</option>
    <option value="mango">Mango</option>
    <option value="aguacate">Aguacate (Palto)</option>
    <option value="guayaba">Guayaba</option>
</optgroup>